### PR TITLE
PMC: IREO support and README rewrite.

### PR DESCRIPTION
**Pull request by PlatinumMaster**
PMC has been confirmed working on Black 2 after providing a proper external symbol database & a proper assembly interface. Furthermore, I felt the README was lacking a bit in instructions, so I updated this as well.

Not ready to merge yet, however. 
- CTRMap needs to be updated to allow Black 2 code injection (I have done so locally, but need to push changes after cleaning up).
- I still want to clean up `swan` to have an ESDB ready to link with Black 2.

### CODE REVIEW

**Comment by HelloOO7** [comment]
The README looks good, but I'm not a huge fan of having the interface split into files per each game. Originally it was alright to use hardcoded adresses, as we only targeted W2. If more games are to be targeted, we should strive to achieve link-time compatibility through the RPM prelinker (when installing the PMC.rpm through CTRMap), as to not require a separate build/RPM for every game. Meaning that instead of absolute addresses (0x02005050), we should use symbol-relative placement (symbol+offset), so that one RPM can be used while changing only the ESDBs. Is there anything that would prevent us from doing that?

On a side note, since PMC was built using the VSCode CMake tools on Windows, I should probably add that to the README's build instructions as well.

**Comment by PlatinumMaster** [comment]
The structures of the functions in Black 2 are relatively the same, so I think it'd be fine for that game at least. Other games (i.e Black, White) I think are also similar, but would require a separate interface since some functions are a different size (so relative offsets might not work here).

Link-time compatibility would be perfect, but for non-swan games I'm not sure how to go about it. Maybe just a build for `WB` and a build for `SWAN`?

**Comment by HelloOO7** [comment]
Personally, I would say that we'll get there when we get there. However, I think that most of the functions that PMC uses (C stdlib, nn::fs, gfl::core) should be available in all of the games.

The only thing that could pose a problem is the area of the actual injection - though if you used the DS secure area (where Nintendo usually put some random bytes during lotchecks that iirc didn't serve any run-time purpose), then it would be the same for all games.

As for game-specific constants like the start of heap memory - that should not be an issue since the value is overwritten by CTRMap when the RPM is installed.

**Comment by PlatinumMaster** [comment]
Yeah, I can personally confirm that a lot of the GFL functions are in `WB` games as well, so that shouldn't be too hard to work with. Only thing is that some might be a bit different in size.

I assume the secure area is executable? Maybe there's some other region of memory we can keep it if not. I do know that in White 1 (IRAO), SDK strings are in the same location.

Also yeah, I also modified CTRMapV for this purpose; didn't upstream the changes yet though. When I do I'll mark this as ready for review.

**Comment by HelloOO7** [comment]
If I'm not mistaken, all of main memory and ITCM should be RWX in system mode.

Again, though, this is a puzzle to be solved later, if it actually becomes a talking point. For now, as far as W2 and B2 go, the solution would be to get rid of the hardcoded addresses in the assembly hooks (where needed). That basically means either making sure that the GameInit code is in the same place in both games, or we can find a different point of insertion - that should now be more flexible since PMC no longer relies on GFL for overlay and memory management.

**Comment by HelloOO7** [comment]
I changed PMC_AsmInterface.s in the [shared-interface](https://github.com/kingdom-of-ds-hacking/PMC/tree/shared-interface) branch to:
- Inject directly into main() after the GFLAppInit call (I deemed it more practical than SystemInit since people may want to use GFL heap management and utilities in DllMain).
- Store the bootcode in the secure area - at 0x0200400C. This region should only contain some SVC calls and game-specific random garbage data and there should be enough space at this address that the bootcode won't corrupt the running code present in the region. That needs to be confirmed on B2 though.
- Refer to the heap start and overlay count symbols by names instead of addresses.

I've confirmed this to work for a clean copy of W2 with NitroKernel and PrintService loading and working as expected. Can you verify if this is also the case for B2? Note that some changes to CTRMap have to be made to properly modify the AdjustHeapStart value - see the [portable-pmc-cis](https://github.com/kingdom-of-ds-hacking/CTRMapV/tree/portable-pmc-cis) branch.

**Comment by PlatinumMaster** [comment]
Replaced by #2.

**Pull request closed without merging**
